# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: shapelib 0.7.1 ruby lib
# stub: ext/shapelib_ext/extconf.rb

Gem::Specification.new do |s|
  s.name = "shapelib".freeze
  s.version = "0.7.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["prasinos@users.sourceforge.net".freeze, "Mike Mangino".freeze, "Mike Perham".freeze]
  s.date = "2024-05-02"
  s.description = "Simple wrapper around the shapelib library".freeze
  s.email = "mmangino@elevatedrails.com".freeze
  s.extensions = ["ext/shapelib_ext/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "doc/Interface.html",
    "doc/Interface.rd",
    "doc/style.css",
    "ext/shapelib_ext/depend",
    "ext/shapelib_ext/extconf.rb",
    "ext/shapelib_ext/main.c",
    "ext/shapelib_ext/sfcode.h",
    "ext/shapelib_ext/sflist.h",
    "ext/shapelib_ext/shpplus.c",
    "ext/shapelib_ext/shpplus.h",
    "ext/shapelib_ext/spcode.h",
    "ext/shapelib_ext/splist.h",
    "ext/shapelib_ext/spwkt.h",
    "ext/shapelib_ext/valconv.h",
    "lib/shapelib.rb",
    "lib/shapelib/shape.rb",
    "lib/shapelib/version.rb",
    "shapelib.gemspec",
    "test/data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.dbf",
    "test/data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.prj",
    "test/data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.shp",
    "test/data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.shp.xml",
    "test/data/ZillowNeighborhoods-CA/ZillowNeighborhoods-CA.shx",
    "test/test_zillow_data.rb"
  ]
  s.homepage = "http://github.com/mperham/shapelib".freeze
  s.rubygems_version = "3.1.2".freeze
  s.summary = "Simple wrapper around the shapelib library".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<rake-compiler>.freeze, [">= 0.7.0"])
  else
    s.add_dependency(%q<rake-compiler>.freeze, [">= 0.7.0"])
  end
end

